.PATH:	${.CURDIR}/../../wsutil

SRCS+= airpdcap_wep.c \
	crash_info.c \
	crc10.c \
	crc16.c \
	crc16-plain.c \
	crc32.c \
	crc6.c \
	crc7.c \
	crc8.c \
	crc11.c \
	crcdrm.c \
	mpeg-audio.c \
	privileges.c \
	str_util.c \
	type_util.c

CFLAGS+=	-I${.CURDIR}/../../ -I/usr/local/include/glib-2.0
