.PATH: ${.CURDIR}/../../epan/crypt

SRCS+=	\
	aes.c \
	airpdcap.c \
	airpdcap_ccmp.c \
	airpdcap_debug.c \
	airpdcap_rijndael.c \
	airpdcap_tkip.c \
	des.c \
	eax.c \
	md4.c \
	md5.c \
	rc4.c \
	sha1.c
